services:
  backend:
    build:
      args:
        PYTHON_IMAGE: registry.cn-hangzhou.aliyuncs.com/library/python:3.13-slim
        PIP_INDEX_URL: https://mirrors.aliyun.com/pypi/simple
  frontend:
    build:
      args:
        NODE_IMAGE: registry.cn-hangzhou.aliyuncs.com/library/node:20-alpine
        NPM_REGISTRY: https://registry.npmmirror.com
