collection_name: agent
persist_dir: resources/chroma
k: 3
data_path: resources/data
stored_data: resources/data/stored.log
allow_knowledge_file_type: ["txt","pdf"]

chunk_size: 800
chunk_overlap: 80
separators: [
    "\n\n",
    "\n",
    "。", "．",
    ".",
    "；", ";",
    "！", "!",
    "？", "?",
    "，", ",",
    " ",
    ""
]